# Generated by Django 3.2.6 on 2021-08-27 23:13

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=django.db.models.fields.IntegerField)),
                ('nickname', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=30)),
                ('registarration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
